version: 0.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: AirFailoverWatchdog.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a AirFailoverWatchdog-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\AirFailoverWatchdog\bin\release\AirFailoverWatchdog.exe
    7z a AirFailoverWatchdog-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\AirFailoverWatchdog\bin\release\settings.xml

    appveyor PushArtifact AirFailoverWatchdog-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip
    
    7z a AirFailoverWatchdog-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\AirFailoverWatchdog\bin\release

    appveyor PushArtifact AirFailoverWatchdog-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip